# Generated by Django 4.2 on 2024-07-22 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='brand')),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('flag', models.CharField(choices=[('SOHAG', 'SOHAG'), ('AKHMEM', 'AKHMEM'), ('GIRGA', 'GIRGA'), ('RED-SEA', 'RED-SEA')], max_length=20, verbose_name='flag')),
                ('price', models.FloatField(verbose_name='price')),
                ('image', models.ImageField(upload_to='gym', verbose_name='image')),
                ('sku', models.IntegerField()),
                ('subtitle', models.TextField(max_length=400, verbose_name='subtitle')),
                ('discription', models.TextField(max_length=2000, verbose_name='discription')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gym_brand', to='products.brand', verbose_name='brand')),
            ],
        ),
        migrations.CreateModel(
            name='GymImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gymimages')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_images', to='products.gym')),
            ],
        ),
    ]
