# Generated by Django 4.2 on 2024-07-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
